config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  get 'dashboard/index'
  
  resources :users do
    resources :exercises
  end
  
  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end
  
  resources :friendships, only: [:show, :create, :destroy]

  root to: 'dashboard#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
    belongs_to :user
    
    validates :duration_in_min, presence: true
    validates :duration_in_min, numericality: { only_integer: true }
    validates :workout, presence: true
    validates :workout_date, presence: true
    validates :user_id, presence: true
    
    default_scope { where('workout_date > ?', 7.days.ago).order(workout_date: :desc) }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :exercises 
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  self.per_page = 10
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def self.search_by_name(name)
    names_array = name.split(' ')
    if names_array.size == 1
      where('first_name LIKE ? or last_name LIKE ?',
        "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name LIKE ? or first_name LIKE ? or last_name LIKE ? or last_name LIKE ?', 
    "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end
  end

  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end

  def current_friendship(friend)
    friendships.where(friend: friend).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @athletes = User.paginate(:page => params[:page])
  end
  
  def search
    @athletes = User.search_by_name(params[:search_name]).paginate(:page => params[:page])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_exercise, except: [:index, :new, :create]
    
    def index
        @exercises = current_user.exercises.all
        @friends = current_user.friends
    end
    
    def new
        @exercise = current_user.exercises.new
    end
    
    def create
        @exercise = current_user.exercises.new(exercise_params)
        if @exercise.save
          flash[:success] = "Exercise has been created"
          redirect_to [current_user, @exercise]
        else
          flash[:danger] = "Exercise has not been created"
          render :new
        end
    end
    
    def edit
    
    end
    
    def update
        if @exercise.update(exercise_params)
          flash[:success] = "Exercise has been updated"
          redirect_to [current_user, @exercise]
        else
          flash[:danger] = "Exercise has not been updated"
          render :edit
        end
    end
    
    def show
        
    end
    
    def destroy
        @exercise.destroy
        flash[:success] = "Exercise has been deleted"
        redirect_to user_exercises_path(current_user)
    end
    
    private
  
      def exercise_params
        params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
      end
      
      def set_exercise
        @exercise = current_user.exercises.find(params[:id])
      end
    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    friend = User.find(params[:friend_id])
    Friendship.create(friendship_params.merge!(friend_id: params[:friend_id], 
      user_id: current_user.id)) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end
  
  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises.all
  end
  
  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship.destroy
      flash[:success] = "#{@friendship.friend.full_name} unfollowed"
    else
      flash[:danger] = "#{@friendship.friend.full_name} could not be unfollowed"
    end
    redirect_to user_exercises_path(current_user)
  end
  
  private 
  
  def friendship_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private 
    
    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
    
    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, 
          :current_password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def devise_error_messages!
        return '' if resource.errors.empty?
            messages = resource.errors.full_messages.map {
            |msg| content_tag(:li, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-danger">
            <a href='#' class='close' data-dismiss='alert' &#215;></a>
            <%= content_tag :div, msg if msg.is_a?(String) %>
            </div>
            HTML
            html.html_safe
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron" >
  <h2 style="color:black">The</h2>
  <h1>Workout Lounge!</h1>
  <p>Share your workouts with your friends and family</p>
</div>

<div class="row">
  <div class="col-md-10">
    <h2>List of Members</h2>
    <%= will_paginate @athletes, renderer: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @athletes.each do |athlete| %>
    <div class="col-md-10 well member">
      <%= athlete.full_name %>
      <% if current_user %>
        <%= link_to "Follow", friendships_path(friend_id: athlete.id), method: :post, 
              class: "btn btn-primary pull-right" unless current_user.follows_or_same?(athlete) %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/search.html.erb
<div class="container">
  <div class="row search-result">
    <% @athletes.each do |athlete| %>
    <div class="col-md-10 col-xs-offset-1 well member">
      <%= athlete.full_name %>
      <% if current_user %>
        <%= link_to "Follow", friendships_path(friend_id: athlete.id), method: :post, 
              class: "btn btn-primary pull-right" unless current_user.follows_or_same?(athlete) %>
      <% end %>
    </div>
    <% end %>
  </div>
  <%= will_paginate @athletes, renderer: BootstrapPagination::Rails %>
</div>

app/views/exercises/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for([current_user, @exercise], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exercise.errors.count, "error") %>
            prohibited this exercise from being saved: </h2>
          <ul>
            <% @exercise.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class="col-md-10">
          <%= f.number_field :duration_in_min, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout Details" %><br>
        </div>
        <div class="col-md-10">
          <%= f.text_area :workout, class: "form-control", rows: "10" %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout_date, "Activity date" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :workout_date, class: "form-control", id: "exercise_workout_date" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">Editing Exercises for : <%= current_user.full_name %></h1>

<%= render 'form' %>
<%= link_to "Show", [current_user, @exercise] %>
<%= link_to "Back", user_exercises_path(current_user) %>

app/views/exercises/index.html.erb
<div class="col-md-8 col-xs-12">
  <% unless @exercises.empty? %>
  <h1>Listing Exercises</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Workout details</th>
        <th>Activity date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.duration_in_min %></td>
        <td><%= truncate(exercise.workout, length: 100) %></td>
        <td><%= exercise.workout_date %></td>
        <td><%= link_to "Show", [current_user, exercise] %></td>
        <td><%= link_to "Edit", [:edit, current_user, exercise] %></td>
        <td><%= link_to "Destroy", [current_user, exercise], method: :delete, 
                                    data: { confirm: "Are you sure?" } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% else %>
  <div class="alert alert-danger message-font text-center" role="alert">
    No Workouts yet
  </div>
  <br>
  <% end %>
  <%= link_to "New Workout", new_user_exercise_path(current_user), class: "btn btn-primary link" %>
  <%= content_tag :div, "", id: "chart", data: {workouts: @exercises} %>
</div>

<div class="col-md-4 col-xs-12">
  <h1 class="text-center">My Friends</h1>
  <% @friends.each do |friend| %>
    <div class="col-md-offset-3 col-md-6 friend_name">
      <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
    </div>
    <div class="col-md-3">
      <div class="btn-unfollow">
        <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)), method: :delete,
          data: {confirm: "Are you sure?"}, class: "btn btn-primary link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-10 col-md-offset-2">
          <%= link_to "Back", user_exercises_path(current_user), class: "btn btn-primary link", id: "new-exer-btn" %>
        </div>
    </div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details" %></h2>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout details:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
  <br>
  <br>
  <div class="col-xs-12 col-md-10 member">
    <%= link_to "Back", user_exercises_path(current_user) %>
  </div>
</div>

app/views/friendships/show.html.erb
<div class="col-md-8">
  <p id="notice"><%= notice %></p>
  
  <h1><%= @friend.full_name %>'s Exercises</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Workout Details</th>
        <th>Activity Date</th>
      </tr>
    </thead>
    
    <tbody>
      <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.duration_in_min %></td>
        <td><%= truncate(exercise.workout, length: 100) %></td>
        <td><%= exercise.workout_date %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  <%= content_tag :div, "", id: "chart", data: {workouts: @exercises} %>
  
  <br>
  <%= link_to "Back", user_exercises_path(current_user), class: "btn btn-primary link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
  <%= render 'shared/main' %>
</body>
</html>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
          data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>  
        <%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %>
            <span class="sr-only">(current)</span>
          </li>
        </ul>
        <%= form_tag(search_dashboard_path, class: "navbar-form navbar-left", role: "search") do %>
        <div class="form-group">
          <%= text_field_tag :search_name, nil, placeholder: "Search for friends", class: "form-control" %>
        </div>
        <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "My Lounge", user_exercises_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <div class="navbar-right">
              <p class="navbar-text">
                Signed in as <%= "#{current_user.email}" %>
              </p>
            </div>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>        
  </nav>
  <br>
  <br>
</header>

app/views/shared/_main.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href='#' class='close' data-dismiss='alert'>&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
    <%= yield %>
</div>